version: "1"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - errcheck
    - unused
    - typecheck

linters-settings:
  gofmt:
    simplify: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: package-comments
      - name: blank-imports

  errcheck:
    exclude-functions:
      # Tambahkan fungsi yang ingin di-ignore (jika ada)
      # - fmt.Fprintf
      # - io.Copy

issues:
  exclude-dirs:
    - vendor
    - tmp
    - tempo-data
    - coverage

  exclude-files:
    - ".*_test.go"

  max-issues-per-linter: 0
  max-same-issues: 0