version: "1"

run:
  timeout: 2m
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode
  disable:
    - gocyclo
    - megacheck
    - goconst
    - dupl

linters-settings:
  gofmt:
    simplify: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: package-comments
      - name: blank-imports

  errcheck:
    exclude-functions:
      # Tambahkan fungsi yang ingin di-ignore (jika ada)
      # - fmt.Fprintf
      # - io.Copy

issues:
  exclude-dirs:
    - vendor
    - tmp
    - tempo-data
    - coverage

  exclude-files:
    - ".*_test.go"

  max-issues-per-linter: 0
  max-same-issues: 0