# Gunakan image resmi Go sebagai base image
FROM golang:1.24 AS builder

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/local/bin

# Set Working Directory
WORKDIR /app

# Copy go.mod dan go.sum terlebih dahulu
COPY go.mod go.sum ./
COPY vendor/ ./vendor/

# Install dependensi
RUN go mod tidy

# Copy semua file ke dalam container
COPY . .
COPY .air.toml ./

# Pastikan direktori tmp ada (untuk menampung binary hasil build)
RUN mkdir -p tmp

#Expose port aplikasi
EXPOSE 8080

# Jalankan aplikasi
CMD ["air"]