server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: oncomapi
    static_configs:
      - targets:
          - localhost
        labels:
          job: oncomapi
          __path__: /var/log/oncomapi/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            trace_id: trace_id
            user_id: user_id
            method: method
            path: path
            latency: latency
            message: message
            timestamp: timestamp
            payload: payload
            log_type: log_type
      - labels:
          trace_id: ""
          user_id: ""
          path: ""
          method: ""
          level: ""
          log_type: ""