name: Deploy to Development Server

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/oncomapi:dev
            docker stop oncomapi-dev || true && docker rm oncomapi-dev || true
            docker run -d --name oncomapi-dev -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/oncomapi:dev