basePath: /api
definitions:
  dto.ArticleResponse:
    properties:
      content:
        type: string
      id:
        type: integer
      slug:
        type: string
      title:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        example: 404
        type: integer
      data:
        type: object
      message:
        example: Data tidak ditemukan
        type: string
      status:
        example: Not Found
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for calendarapi.
  title: calendarapi
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/dto.ArticleResponse"
            type: array
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/response.ErrorResponse"
      security:
        - BearerAuth: []
      summary: Get all articles
      tags:
        - Article
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
