name: Build Dev Docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/oncomapi:latest -f Dockerfile.stg .
        docker push ${{ secrets.DOCKER_USERNAME }}/oncomapi:latest
