name: Build Dev Docker image

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Tags
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        echo "ref_name=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image with multiple tags (multi-platform)
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
        -f Dockerfile.dev.sample \
        -t ${{ secrets.DOCKER_USERNAME }}/oncomapi:dev-${{ steps.vars.outputs.sha_short }} \
        -t ${{ secrets.DOCKER_USERNAME }}/oncomapi:dev \
        -t ${{ secrets.DOCKER_USERNAME }}/oncomapi:${{ steps.vars.outputs.ref_name }} \
        --push .