name: CI Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./... -coverprofile=coverage.out