name: Deploy to Main Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MAIN_EC2_HOST }}
          username: ${{ secrets.MAIN_EC2_USER }}
          key: ${{ secrets.MAIN_EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/oncomapi:latest
            docker stop oncomapi-main || true && docker rm oncomapi-main || true
            docker run -d --name oncomapi-main -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/oncomapi:latest
