name: Deploy to Development Server

on:
  workflow_run:
    workflows: ["Build Dev Docker image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Get Portainer JWT
      id: auth
      run: |
        echo "Logging in..."
        echo "PORTAINER_URL: $PORTAINER_URL"
        echo "PORTAINER_USERNAME: $PORTAINER_USERNAME"
        echo "PORTAINER_PASSWORD: $PORTAINER_PASSWORD"
        echo "Response from auth:"
        response=$(curl -s -X POST "$PORTAINER_URL/api/auth" \
          -H "Content-Type: application/json" \
          -d '{"Username": "'"$PORTAINER_USERNAME"'", "Password": "'"$PORTAINER_PASSWORD"'"}'
        )
        token=$(echo $response | jq -r '.jwt')
        echo "token: $token"
        echo "token=$token" >> $GITHUB_OUTPUT
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
        PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}

    - name: Test connectivity to Docker Hub Registry
      run: |
        echo "Testing connection to Docker Hub Registry..."
        curl -v https://registry-1.docker.io/v2/ || exit 1

    - name: Pull docker image from Docker hub
      run: |
        for i in {1..3}; do
          response=$(curl -s -X POST "$PORTAINER_URL/api/endpoints/$PORTAINER_ENDPOINT_ID/docker/images/create?fromImage=oncomtech/oncomapi&tag=dev" \
            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}"
          )
          
          echo "Pull response: $response"

          if echo "$response" | grep -q '"error"'; then
            echo "Pull failed, retrying ($i)..."
            sleep 5
          else
            echo "Pull successful"
            break
          fi
        done
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}

    - name: Remove existing container (if exists)
      run: |
        curl -s -X DELETE "$PORTAINER_URL/api/endpoints/$PORTAINER_ENDPOINT_ID/docker/containers/oncomapi-dev?force=true" \
          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}"
      continue-on-error: true
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}

    - name: Create and start new container
      run: |
        curl -s -X POST "$PORTAINER_URL/api/endpoints/$PORTAINER_ENDPOINT_ID/docker/containers/create?name=oncomapi-dev" \
          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d '{
            "Image": "oncomtech/oncomapi:dev",
            "HostConfig": {
              "PortBindings": {
                "8080/tcp": [{"HostPort": "8080"}]
              },
              "RestartPolicy": {
                "Name": "always"
              }
            }
          }'

        curl -s -X POST "$PORTAINER_URL/api/endpoints/$PORTAINER_ENDPOINT_ID/docker/containers/oncomapi-dev/start" \
          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}"
      
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}
