name: Deploy to Staging Server

on:
  push:
    branches: [stg]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STG_EC2_HOST }}
          username: ${{ secrets.STG_EC2_USER }}
          key: ${{ secrets.STG_EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/oncomapi:stg
            docker stop oncomapi-stg || true && docker rm oncomapi-stg || true
            docker run -d --name oncomapi-stg -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/oncomapi:stg
